routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Message;

Route::get('/', function () {
    return view('welcome');
});

Route::resource('messages', 'MessageController');

app/Message.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Message extends Model
{
	protected $fillable = [
		'name',
		'email',
		'subject',
		'message'
	];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/MessageController.php
<?php

namespace App\Http\Controllers;

use App\Message;
use Illuminate\Support\Facades\Mail;
use App\Mail\NewSubmissionOwner;
use App\Mail\NewSubmissionUser;
use Illuminate\Http\Request;

class MessageController extends Controller
{
    public function index() {
    	return view('messages.index', [ 'messages' => Message::all()]);
    }

    public function create() {
		return view('messages.create');
    }

    public function store(Request $request) {
		$request->validate([
			'name' => 'required',
			'email' => 'required|email',
			'subject' => 'required',
			'message' => 'required'
		]);
		$message = new Message([
			'name' => $request->get('name'),
			'email' => $request->get('email'),
			'subject' => $request->get('subject'),
			'message' => $request->get('message'),
		]);
		$message->save();
	    Mail::to('jessica@jessica-plant.co.uk')->send(new NewSubmissionOwner($message));
	    Mail::to($message->email)->send(new NewSubmissionUser());
		return redirect('/messages')->with('success', 'Your message has been successfully saved');
    }
}

resources/views/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
@yield('content')
</body>
</html>

resources/views/messages/create.blade.php
@extends('layout')

@section('content')
    <div class="jumbotron">
        <div class="container">
            <h1>Create a Message</h1>
        </div>
    </div>
    @if ($errors->any())
        <div class="container">
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        </div>
    @endif
    <div class="container">
        <form method="post" action="{{ route('messages.store') }}">
            <div class="form-group">
                <label for="name">Name: </label>
                <input type="text" class="form-control" name="name">
            </div>
            <div class="form-group">
                <label for="email">Email: </label>
                <input type="email" class="form-control" name="email">
            </div>
            <div class="form-group">
                <label for="subject">Subject: </label>
                <input type="text" class="form-control" name="subject">
            </div>
            <div class="form-group">
                <label for="message">Message: </label>
                <textarea class="form-control" name="message" id="message" cols="30" rows="10"></textarea>
            </div>
            {{ csrf_field() }}
            <div class="form-group">
                <input type="submit" value="Send" class="btn btn-primary">
            </div>

        </form>
    </div>

@endsection

resources/views/messages/index.blade.php
@extends('layout')

@section('content')
<div class="jumbotron">
    <div class="container">
        <h1>Your Messages</h1>
        <a class="btn btn-primary" href="{{ route('messages.create') }}">Create</a>
    </div>

</div>
<div class="container">
    <table class="table">
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Subject</th>
            <th>Message</th>
        </tr>
        @foreach ($messages as $message)
            <tr>
                <td>{{ $message->name }}</td>
                <td>{{ $message->email }}</td>
                <td>{{ $message->subject }}</td>
                <td>{{ $message->message }}</td>
            </tr>
        @endforeach
    </table>
</div>

@endsection